version: '3.1'
services:
  backend:
    image: ghcr.io/musikfreunde/eazy-menue-backend:latest
    ports:
      - 8080:8080
    networks:
      - quarkus
  identity-provider:
    image: jboss/keycloak:14.0.0
    volumes:
      - ./eazymenu-realm.json:/tmp/eazymenu-realm.json
      - /keycloak_theme_new:opt/jboss/keycloak/themes/eazymenue
    command: [ '-b', '0.0.0.0', '-Dkeycloak.migration.action=import', '-Dkeycloak.profile.feature.upload_scripts=enabled', '-Dkeycloak.migration.provider=singleFile', '-Dkeycloak.migration.file=/tmp/eazymenu-realm.json' ]
    environment:
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: root
      DB_VENDOR: H2
    ports:
      - 8082:8080
    container_name: eazymenu-identity-provider
    networks:
      - quarkus
  frontend:
    image: ghcr.io/musikfreunde/eazy-menue-frontend:latest
    depends_on:
      - identity-provider
      - backend
    ports:
      - 8083:80
    networks:
      - quarkus
networks:
  quarkus:
    driver: bridge
