version: '3.1'
services:
#  backend:
#    image: ghcr.io/musikfreunde/leocode-backend:25.0
#    container_name: backend
#    volumes:
#      - projects-in-queue:../../projects-in-queue
#    environment:
#      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres-db:5432/db
#      - QUARKUS_HTTP_CORS_METHODS=*
#      - QUARKUS_HTTP_CORS=true
#      - QUARKUS_HTTP_CORS_ORIGINS=*
#      - QUARKUS_HTTP_CORS_HEADERS=*
#      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#    depends_on:
#      - postgres-db
#      - kafka
#    ports:
#      - "8181:9090"
#    networks:
#      - quarkus
  identity-provider:
    image: jboss/keycloak:14.0.0
    volumes:
      - ./eazymenu-realm.json:/tmp/eazymenu-realm.json
    command: [ '-b', '0.0.0.0', '-Dkeycloak.migration.action=import', '-Dkeycloak.profile.feature.upload_scripts=enabled', '-Dkeycloak.migration.provider=singleFile', '-Dkeycloak.migration.file=/tmp/eazymenu-realm.json' ]
    environment:
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: root
      DB_VENDOR: H2
    ports:
      - 8082:8080
    container_name: eazymenu-identity-provider
    networks:
      - quarkus
networks:
  quarkus:
    driver: bridge
