http://localhost:8080/menue/bestellung/spabo

###

http://localhost:8080/menue/bestellung/stats/besbe

###

http://localhost:8080/menue/bestellung/categories/spabo

###

http://localhost:8080/menue/bestellung/categories

###

http://localhost:8080/menue/menues

###


